### PR TITLE
Add extra magnitude system and units

### PR DESCRIPTION
**Pull request by cquiroz**
ITC uses a couple of extra magnitude systems. We may want to let users set magnitudes with them in the UI too

I learned mag systems may have units and I thought to include them in the encoding

### CODE REVIEW

**Comment by swalker2m** [comment]
> We may want to let users set magnitudes with them in the UI too

Seems like you'll have to at least display them since they now can appear in the model.

**Review by swalker2m — APPROVED** [review]
I'm not sure what we'll do with this but it seems good to have. :+1:

**Comment by cquiroz** [comment]
Yes they will appear as extra options here:
image(3)

**Comment by andrewwstephens** [comment]
:+1: Definitely useful!

**Pull request merged**
