### PR TITLE
Add obsolete field

### PR DESCRIPTION
**Pull request by cquiroz**
Mark BHROS as obsolete

### CODE REVIEW

**Review by swalker2m — COMMENTED** [review]
I thought this would come from Resource in GPP and be expanded with time intervals for validity etc.  Perhaps I missed a conversation about this.

**Comment by cquiroz** [comment]
Yes, but there is no ETA for that yet, this is now mocked on the ITC and I thought maybe better to push it to `core`

**Review by swalker2m — APPROVED** [review]
> Yes, but there is no ETA for that yet

That certainly a fair point and I'll go ahead and approve.  I kind of fear we'll end up just keeping the boolean flags though.

**Comment by cquiroz** [comment]
I can certainly live without this change and maybe it is a bad signal, let's close it.

**Pull request closed without merging**
