### PR TITLE
Add Eq instance for OrcidProfile and tests

### PR DESCRIPTION
**Pull request by cquiroz**
Add Eq instance for `OrcidProfile`

### CODE REVIEW

**Comment by cquiroz** [comment]
@tpolecat Should we use refined types in `OrcIdProfile`?

**Review by swalker2m — COMMENTED** [review]
Seems good to me.  I'll leave it to @tpolecat to approve though since it's his thing.

**Comment by tpolecat** [comment]
Sorry, I missed this one. @cquiroz what did you want to use refined types for? Did you mean using newtypes for the components so it's not just a bunch of strings?

**Comment by cquiroz** [comment]
Yes basically NonEmptyString in some places, but it is not very important

**Pull request merged**
