### PR TITLE
Add name to user defined SED

### PR DESCRIPTION
**Pull request by cquiroz**
TIL user defined SEDs should have a name

### CODE REVIEW

**Review by swalker2m — APPROVED** [review]
Code looks good.  👍 this will have to bubble through everything of course

Why do they need a name?  What will we do with it?  Are they expecting to reuse them across targets?

**Comment by cquiroz** [comment]
All good questions, I guess the idea is to upload a file name and give it a name so you could refer it in other places

**Comment by cquiroz** [comment]
This is not urgent. Perhaps we should review it when we really implement iTC support for user data

**Comment by swalker2m** [comment]
> Perhaps we should review it when we really implement iTC support for user data

Yeah it seems like the model may have to change more if we want to reference a shared set of flux densities.

**Comment by cquiroz** [comment]
Yeah, let's close this

**Pull request closed without merging**
